// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ChannelsinteractionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.firefox());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void channelview() {
    // Test name: channel view
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/user/gordonramsay | 
    driver.get("https://www.youtube.com/user/gordonramsay");
    // 2 | runScript | window.scrollTo(0,159) | 
    js.executeScript("window.scrollTo(0,159)");
    // 3 | runScript | window.scrollTo(0,171) | 
    js.executeScript("window.scrollTo(0,171)");
    // 4 | click | xpath=//div[@id='tabsContent']/paper-tab[2]/div | 
    driver.findElement(By.xpath("//div[@id=\'tabsContent\']/paper-tab[2]/div")).click();
    // 5 | click | xpath=//div[@id='tabsContent']/paper-tab[3]/div | 
    driver.findElement(By.xpath("//div[@id=\'tabsContent\']/paper-tab[3]/div")).click();
    // 6 | runScript | window.scrollTo(0,285) | 
    js.executeScript("window.scrollTo(0,285)");
    // 7 | click | xpath=//div[@id='tabsContent']/paper-tab[4]/div | 
    driver.findElement(By.xpath("//div[@id=\'tabsContent\']/paper-tab[4]/div")).click();
    // 8 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 9 | click | xpath=//div[@id='tabsContent']/paper-tab[5]/div | 
    driver.findElement(By.xpath("//div[@id=\'tabsContent\']/paper-tab[5]/div")).click();
    // 10 | click | xpath=//div[@id='tabsContent']/paper-tab[6] | 
    driver.findElement(By.xpath("//div[@id=\'tabsContent\']/paper-tab[6]")).click();
    // 11 | click | xpath=(//button[@id='button']/yt-icon)[9] | 
    driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[9]")).click();
    // 12 | click | xpath=//div[@id='tabsContent']/paper-tab[5]/div | 
    driver.findElement(By.xpath("//div[@id=\'tabsContent\']/paper-tab[5]/div")).click();
  }
}
