// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class HistoryTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void historyTest() {
    // Test name: HistoryTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | click | css=.ytp-large-play-button | 
    driver.findElement(By.cssSelector(".ytp-large-play-button")).click();
    // 4 | mouseOver | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.id("guide-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | click | id=guide-icon | 
    driver.findElement(By.id("guide-icon")).click();
    // 6 | mouseOut | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 7 | click | css=.style-scope:nth-child(2) > #items > .style-scope:nth-child(2) > #endpoint .title | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(2) > #items > .style-scope:nth-child(2) > #endpoint .title")).click();
    // 8 | mouseOver | css=.style-scope:nth-child(2) > .yt-simple-endpoint #offRadio | 
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(2) > .yt-simple-endpoint #offRadio"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | click | css=.style-scope:nth-child(2) > .yt-simple-endpoint #offRadio | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(2) > .yt-simple-endpoint #offRadio")).click();
    // 10 | mouseOut | css=.style-scope:nth-child(2) > .yt-simple-endpoint #offRadio | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 11 | mouseOver | css=.style-scope:nth-child(3) #offRadio | 
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(3) #offRadio"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 12 | click | css=.style-scope:nth-child(3) #offRadio | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(3) #offRadio")).click();
    // 13 | mouseOut | css=.style-scope:nth-child(3) #offRadio | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 14 | mouseOver | css=.style-scope:nth-child(4) > .yt-simple-endpoint #offRadio | 
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(4) > .yt-simple-endpoint #offRadio"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 15 | click | css=.style-scope:nth-child(4) > .yt-simple-endpoint #offRadio | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(4) > .yt-simple-endpoint #offRadio")).click();
    // 16 | mouseOut | css=.style-scope:nth-child(4) > .yt-simple-endpoint #offRadio | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 17 | click | css=.style-scope:nth-child(5) #offRadio | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(5) #offRadio")).click();
  }
}
