// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
public class LeaveReviewTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void leaveReviewTest() {
    // Test name: LeaveReviewTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | id=logo-icon-container | 
    {
      WebElement element = driver.findElement(By.id("logo-icon-container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | id=logo-icon-container | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | mouseOver | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.id("guide-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | click | id=guide-icon | 
    driver.findElement(By.id("guide-icon")).click();
    // 7 | mouseOut | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | click | css=.style-scope:nth-child(7) > #items > .style-scope:nth-child(4) > #endpoint .title | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(7) > #items > .style-scope:nth-child(4) > #endpoint .title")).click();
    // 9 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 10 | selectFrame | index=2 | 
    driver.switchTo().frame(2);
    // 11 | click | css=textarea | 
    driver.findElement(By.cssSelector("textarea")).click();
    // 12 | click | css=textarea | 
    driver.findElement(By.cssSelector("textarea")).click();
    // 13 | type | css=textarea | Fisting boy next door
    driver.findElement(By.cssSelector("textarea")).sendKeys("Fisting boy next door");
    // 14 | click | css=uf-material-button:nth-child(1) button | 
    driver.findElement(By.cssSelector("uf-material-button:nth-child(1) button")).click();
  }
}
