// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class LeftMenuTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = Util.getFirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    @SuppressWarnings("unchecked") Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }

  @Test
  public void toHome() {
    // Test name: ToHome
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ |
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 |
    driver.manage().window().setSize(new Dimension(1098, 691));
    String xpathExpression;
    // 3 | mouseOver | xpath=//form/button |
    {
      xpathExpression = "//form/button";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | xpath=//form/button |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | mouseOver | xpath=//yt-icon-button[2]/button/yt-icon |
    {
      xpathExpression = "//yt-icon-button[2]/button/yt-icon";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | click | xpath=//yt-icon-button[2]/button/yt-icon |
    driver.findElement(By.xpath("//yt-icon-button[2]/button/yt-icon")).click();
    // 7 | mouseOut | xpath=//yt-icon-button[2]/button/yt-icon |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | mouseOver | xpath=//div[2]/div/yt-icon-button/button/yt-icon |
    {
      xpathExpression = "//div[2]/div/yt-icon-button/button/yt-icon";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | mouseOut | xpath=//div[2]/div/yt-icon-button/button/yt-icon |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 10 | click | xpath=//paper-item/yt-formatted-string |
    xpathExpression = "//paper-item/yt-formatted-string";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    Assertions.assertEquals("https://www.youtube.com/", driver.getCurrentUrl());
  }

  @Test
  public void historyTest() {
    // Test name: HistoryTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ |
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 |
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | click | xpath=//div[5]/button |
    String xpathExpression = "//div[5]/button";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    // 4 | mouseOver | xpath=//yt-icon-button[2]/button/yt-icon |
    {
      xpathExpression = "//yt-icon-button[2]/button/yt-icon";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | click | xpath=//yt-icon-button[2]/button/yt-icon |
    xpathExpression = "//yt-icon-button[2]/button/yt-icon";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    // 6 | mouseOut | xpath=//yt-icon-button[2]/button/yt-icon |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 7 | click | css=.style-scope:nth-child(2) > #items > .style-scope:nth-child(2) > #endpoint .title |
    driver.findElement(By.cssSelector(".style-scope:nth-child(2) > #items > .style-scope:nth-child(2) > #endpoint .title")).click();
    Assertions.assertEquals("https://www.youtube.com/feed/history", driver.getCurrentUrl());
    // 8 | mouseOver | css=.style-scope:nth-child(2) > .yt-simple-endpoint #offRadio |
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(2) > .yt-simple-endpoint #offRadio"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | click | css=.style-scope:nth-child(2) > .yt-simple-endpoint #offRadio |
    driver.findElement(By.cssSelector(".style-scope:nth-child(2) > .yt-simple-endpoint #offRadio")).click();
    Assertions.assertEquals("https://www.youtube.com/feed/history/search_history", driver.getCurrentUrl());
    // 10 | mouseOut | css=.style-scope:nth-child(2) > .yt-simple-endpoint #offRadio |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 11 | mouseOver | css=.style-scope:nth-child(3) #offRadio |
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(3) #offRadio"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 12 | click | css=.style-scope:nth-child(3) #offRadio |
    driver.findElement(By.cssSelector(".style-scope:nth-child(3) #offRadio")).click();
    Assertions.assertEquals("https://www.youtube.com/feed/history/comment_history", driver.getCurrentUrl());
    // 13 | mouseOut | css=.style-scope:nth-child(3) #offRadio |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 14 | mouseOver | css=.style-scope:nth-child(4) > .yt-simple-endpoint #offRadio |
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(4) > .yt-simple-endpoint #offRadio"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 15 | click | css=.style-scope:nth-child(4) > .yt-simple-endpoint #offRadio |
    driver.findElement(By.cssSelector(".style-scope:nth-child(4) > .yt-simple-endpoint #offRadio")).click();
    Assertions.assertEquals("https://www.youtube.com/feed/history/community_history", driver.getCurrentUrl());
    // 16 | mouseOut | css=.style-scope:nth-child(4) > .yt-simple-endpoint #offRadio |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 17 | click | css=.style-scope:nth-child(5) #offRadio |
    driver.findElement(By.cssSelector(".style-scope:nth-child(5) #offRadio")).click();
    Assertions.assertEquals("https://www.youtube.com/feed/history/live_chat_history", driver.getCurrentUrl());
  }

  @Test
  public void leaveReviewTest() {
    // Test name: LeaveReviewTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ |
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1488x892 |
    driver.manage().window().setSize(new Dimension(1488, 892));
    // 3 | mouseOver | xpath=//yt-icon-button[2]/button/yt-icon |
    String xpathExpression;
    {
      xpathExpression = "//yt-icon-button[2]/button/yt-icon";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | xpath=//yt-icon-button[2]/button/yt-icon |
    xpathExpression = "//yt-icon-button[2]/button/yt-icon";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath("//yt-icon-button[2]/button/yt-icon")).click();
    // 5 | mouseOut | xpath=//yt-icon-button[2]/button/yt-icon |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | mouseOver | xpath=//div[2]/div/yt-icon-button/button/yt-icon |
    {
      xpathExpression = "//div[2]/div/yt-icon-button/button/yt-icon";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOut | xpath=//div[2]/div/yt-icon-button/button/yt-icon |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | click | xpath=//ytd-guide-section-renderer[6]/div/ytd-guide-entry-renderer[4]/a/paper-item/yt-formatted-string |
    xpathExpression = "//ytd-guide-section-renderer[6]/div/ytd-guide-entry-renderer[4]/a/paper-item/yt-formatted-string";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    // 9 | click | xpath=//label/button |
    xpathExpression = "//button[@type='submit']";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    // 10 | close |  |
    driver.close();
  }

  @Test
  public void libraryTest() {
    // Test name: LibraryTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | xpath=(//button[@id='button']/yt-icon)[2] | 
    String xpathExpression;
    {
      xpathExpression = "(//button[@id=\'button\']/yt-icon)[2]";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | xpath=(//button[@id='button']/yt-icon)[2] |
    xpathExpression = "(//button[@id=\'button\']/yt-icon)[2]";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    // 5 | mouseOut | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | mouseOver | xpath=(//button[@id='button']/yt-icon)[7] | 
    {
      xpathExpression = "(//button[@id=\'button\']/yt-icon)[7]";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOut | xpath=(//button[@id='button']/yt-icon)[7] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | click | xpath=(//a[@id='endpoint']/paper-item/yt-formatted-string)[4] |
    xpathExpression = "(//a[@id=\'endpoint\']/paper-item/yt-formatted-string)[4]";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    Assertions.assertEquals("https://www.youtube.com/feed/library", driver.getCurrentUrl());
  }

  @Test
  public void referenceTest() {
    // Test name: ReferenceTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ |
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1274x690 |
    driver.manage().window().setSize(new Dimension(1274, 690));
    // 3 | mouseOver | xpath=//yt-icon-button[2]/button/yt-icon |
    String xpathExpression;
    {
      xpathExpression = "//yt-icon-button[2]/button/yt-icon";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | xpath=//yt-icon-button[2]/button/yt-icon |
    xpathExpression = "//yt-icon-button[2]/button/yt-icon";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    // 5 | mouseOut | xpath=//yt-icon-button[2]/button/yt-icon |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | xpath=//ytd-guide-section-renderer[6]/div/ytd-guide-entry-renderer[3]/a/paper-item/yt-formatted-string |
    xpathExpression = "//ytd-guide-section-renderer[6]/div/ytd-guide-entry-renderer[3]/a/paper-item/yt-formatted-string";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
  }

  @Test
  public void reportsTest() {
    // Test name: ReportsTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | xpath=(//button[@id='button']/yt-icon)[2] | 
    String xpathExpression;
    {
      xpathExpression = "(//button[@id=\'button\']/yt-icon)[2]";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | xpath=(//button[@id='button']/yt-icon)[2] | 
    driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[2]")).click();
    // 5 | mouseOut | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | mouseOver | xpath=(//a[@id='logo']/div)[3] | 
    {
      xpathExpression = "(//a[@id=\'logo\']/div)[3]";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOut | xpath=(//a[@id='logo']/div)[3] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 9 | click | xpath=(//a[@id='endpoint']/paper-item/yt-formatted-string)[18] |
    xpathExpression = "(//a[@id=\'endpoint\']/paper-item/yt-formatted-string)[18]";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    // 10 | click | xpath=//div[@id='introduction-text']/div[2] |
    xpathExpression = "//div[@id=\'introduction-text\']/div[2]";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    // 11 | click | linkText=принципы сообщества | 
    vars.put("window_handles", driver.getWindowHandles());
    // 12 | selectWindow | handle=${win332} | 
    driver.findElement(By.linkText("принципы сообщества")).click();
    vars.put("win332", waitForWindow(2000));
    driver.switchTo().window(vars.get("win332").toString());
  }

  @Test
  public void settingsTest() {
    // Test name: SettingsTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | xpath=//a[@id='logo']/div | 
    String xpathExpression;
    {
      xpathExpression = "//a[@id=\'logo\']/div";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | xpath=//a[@id='logo']/div | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | click | xpath=//div[@id='start']/yt-icon-button[2] |
    xpathExpression = "//div[@id=\'start\']/yt-icon-button[2]";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    // 6 | mouseOver | xpath=(//a[@id='logo']/div)[3] | 
    {
      xpathExpression = "(//a[@id=\'logo\']/div)[3]";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | click | xpath=(//a[@id='endpoint']/paper-item/yt-formatted-string)[17] |
    xpathExpression = "(//a[@id=\'endpoint\']/paper-item/yt-formatted-string)[17]";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    Assertions.assertFalse(driver.getCurrentUrl().startsWith("https://www.youtube.com")); // moved to google sso page
  }

  @Test
  public void subscriptionsTest() {
    // Test name: SubscriptionsTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | xpath=(//button[@id='button']/yt-icon)[2] | 
    String xpathExpression;
    {
      xpathExpression = "(//button[@id=\'button\']/yt-icon)[2]";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | xpath=(//button[@id='button']/yt-icon)[2] |
    xpathExpression = "(//button[@id=\'button\']/yt-icon)[2]";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    // 5 | mouseOut | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | xpath=(//a[@id='endpoint']/paper-item/yt-formatted-string)[3] |
    xpathExpression = "(//a[@id=\'endpoint\']/paper-item/yt-formatted-string)[3]";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    Assertions.assertEquals("https://www.youtube.com/feed/subscriptions", driver.getCurrentUrl());
  }

  @Test
  public void trendingTest() {
    // Test name: TrendingTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | xpath=(//button[@id='button']/yt-icon)[2] | 
    String xpathExpression;
    {
      xpathExpression = "(//button[@id=\'button\']/yt-icon)[2]";
      Util.waitForPresence(driver, xpathExpression);
      WebElement element = driver.findElement(By.xpath(xpathExpression));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | xpath=(//button[@id='button']/yt-icon)[2] |
    xpathExpression = "(//button[@id=\'button\']/yt-icon)[2]";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    // 5 | mouseOut | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | xpath=(//a[@id='endpoint']/paper-item/yt-formatted-string)[2] |
    xpathExpression = "(//a[@id=\'endpoint\']/paper-item/yt-formatted-string)[2]";
    Util.waitForPresence(driver, xpathExpression);
    driver.findElement(By.xpath(xpathExpression)).click();
    Assertions.assertEquals("https://www.youtube.com/feed/trending", driver.getCurrentUrl());
  }
}
