// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class LeftMenuTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    @SuppressWarnings("unchecked") Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }

  @Test
  public void toHome() {
    // Test name: ToHome
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | xpath=//form[@id='search-form']/button | 
    {
      WebElement element = driver.findElement(By.xpath("//form[@id=\'search-form\']/button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | xpath=//form[@id='search-form']/button | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | mouseOver | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | click | xpath=(//button[@id='button']/yt-icon)[2] | 
    driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[2]")).click();
    // 7 | mouseOut | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | mouseOver | xpath=(//button[@id='button']/yt-icon)[7] | 
    {
      WebElement element = driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[7]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | mouseOut | xpath=(//button[@id='button']/yt-icon)[7] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 10 | click | xpath=//a[@id='endpoint']/paper-item/yt-formatted-string | 
    driver.findElement(By.xpath("//a[@id=\'endpoint\']/paper-item/yt-formatted-string")).click();
  }

  @Test
  public void historyTest() {
    // Test name: HistoryTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | click | xpath=//div[@id='movie_player']/div[5]/button | 
    driver.findElement(By.xpath("//div[@id=\'movie_player\']/div[5]/button")).click();
    // 4 | mouseOver | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | click | xpath=(//button[@id='button']/yt-icon)[2] | 
    driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[2]")).click();
    // 6 | mouseOut | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 7 | click | xpath=(//a[@id='endpoint']/paper-item/yt-formatted-string)[5] | 
    driver.findElement(By.xpath("(//a[@id=\'endpoint\']/paper-item/yt-formatted-string)[5]")).click();
    // 8 | mouseOver | xpath=(//div[@id='radioContainer']/div)[3] | 
    {
      WebElement element = driver.findElement(By.xpath("(//div[@id=\'radioContainer\']/div)[3]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | click | xpath=(//div[@id='radioContainer']/div)[3] | 
    driver.findElement(By.xpath("(//div[@id=\'radioContainer\']/div)[3]")).click();
    // 10 | mouseOut | xpath=(//div[@id='radioContainer']/div)[3] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 11 | mouseOver | xpath=(//div[@id='radioContainer']/div)[5] | 
    {
      WebElement element = driver.findElement(By.xpath("(//div[@id=\'radioContainer\']/div)[5]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 12 | click | xpath=(//div[@id='radioContainer']/div)[5] | 
    driver.findElement(By.xpath("(//div[@id=\'radioContainer\']/div)[5]")).click();
    // 13 | mouseOut | xpath=(//div[@id='radioContainer']/div)[5] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 14 | mouseOver | xpath=(//div[@id='radioContainer']/div)[7] | 
    {
      WebElement element = driver.findElement(By.xpath("(//div[@id=\'radioContainer\']/div)[7]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 15 | click | xpath=(//div[@id='radioContainer']/div)[7] | 
    driver.findElement(By.xpath("(//div[@id=\'radioContainer\']/div)[7]")).click();
    // 16 | mouseOut | xpath=(//div[@id='radioContainer']/div)[7] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 17 | click | xpath=(//div[@id='radioContainer']/div)[9] | 
    driver.findElement(By.xpath("(//div[@id=\'radioContainer\']/div)[9]")).click();
  }

  @Test
  public void leaveReviewTest() {
    // Test name: LeaveReviewTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1488x892 | 
    driver.manage().window().setSize(new Dimension(1488, 892));
    // 3 | mouseOver | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.id("guide-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | id=guide-icon | 
    driver.findElement(By.id("guide-icon")).click();
    // 5 | mouseOut | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | mouseOver | css=#header > #guide-button #guide-icon | 
    {
      WebElement element = driver.findElement(By.cssSelector("#header > #guide-button #guide-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOut | css=#header > #guide-button #guide-icon | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | click | css=.style-scope:nth-child(7) > #items > .style-scope:nth-child(4) > #endpoint .title | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(7) > #items > .style-scope:nth-child(4) > #endpoint .title")).click();
    // 9 | click | xpath=//textarea | 
    driver.findElement(By.xpath("//textarea")).click();
    // 10 | click | xpath=//textarea | 
    driver.findElement(By.xpath("//textarea")).click();
    // 11 | type | xpath=//textarea | Fisting boy next door\n
    driver.findElement(By.xpath("//textarea")).sendKeys("Fisting boy next door\\n");
    // 12 | click | css=uf-material-button:nth-child(1) button | 
    driver.findElement(By.cssSelector("uf-material-button:nth-child(1) button")).click();
    // 13 | close |  | 
    driver.close();
  }

  @Test
  public void libraryTest() {
    // Test name: LibraryTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | xpath=(//button[@id='button']/yt-icon)[2] | 
    driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[2]")).click();
    // 5 | mouseOut | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | mouseOver | xpath=(//button[@id='button']/yt-icon)[7] | 
    {
      WebElement element = driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[7]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOut | xpath=(//button[@id='button']/yt-icon)[7] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | click | xpath=(//a[@id='endpoint']/paper-item/yt-formatted-string)[4] | 
    driver.findElement(By.xpath("(//a[@id=\'endpoint\']/paper-item/yt-formatted-string)[4]")).click();
  }

  @Test
  public void referenceTest() {
    // Test name: ReferenceTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1208x770 | 
    driver.manage().window().setSize(new Dimension(1208, 770));
    // 3 | mouseOver | css=.style-scope:nth-child(2) > #dismissable #video-title | 
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(2) > #dismissable #video-title"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | css=.style-scope:nth-child(2) > #dismissable #video-title | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | mouseOver | css=.style-scope:nth-child(3) > #dismissable #img | 
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(3) > #dismissable #img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | mouseOut | css=.style-scope:nth-child(3) > #dismissable #img | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 7 | mouseOver | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.id("guide-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | click | id=guide-icon | 
    driver.findElement(By.id("guide-icon")).click();
    // 9 | mouseOut | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 10 | click | xpath=(//a[@id='endpoint']/paper-item/yt-formatted-string)[19] | 
    driver.findElement(By.xpath("(//a[@id=\'endpoint\']/paper-item/yt-formatted-string)[19]")).click();
    // 11 | selectFrame | index=2 | 
    driver.switchTo().frame(2);
    // 12 | selectFrame | index=1 | 
    driver.switchTo().frame(1);
    // 13 | click | css=.help-panel-home:nth-child(7) .help-panel-search-result:nth-child(5) > .help-panel-search-result__text > span | 
    driver.findElement(By.cssSelector(".help-panel-home:nth-child(7) .help-panel-search-result:nth-child(5) > .help-panel-search-result__text > span")).click();
    // 14 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 15 | click | css=.help-panel-header__back-icon > path | 
    driver.findElement(By.cssSelector(".help-panel-header__back-icon > path")).click();
    // 16 | click | css=.help-panel-home:nth-child(7) .help-panel-search-result:nth-child(2) > .help-panel-search-result__text > span | 
    driver.findElement(By.cssSelector(".help-panel-home:nth-child(7) .help-panel-search-result:nth-child(2) > .help-panel-search-result__text > span")).click();
    // 17 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 18 | selectFrame | index=7 | 
    driver.switchTo().frame(7);
    // 19 | click | linkText=Android | 
    driver.findElement(By.linkText("Android")).click();
    // 20 | click | css=.index1 | 
    driver.findElement(By.cssSelector(".index1")).click();
    // 21 | click | css=.index2 | 
    driver.findElement(By.cssSelector(".index2")).click();
  }

  @Test
  public void reportsTest() {
    // Test name: ReportsTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | xpath=(//button[@id='button']/yt-icon)[2] | 
    driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[2]")).click();
    // 5 | mouseOut | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | mouseOver | xpath=(//a[@id='logo']/div)[3] | 
    {
      WebElement element = driver.findElement(By.xpath("(//a[@id=\'logo\']/div)[3]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOut | xpath=(//a[@id='logo']/div)[3] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 9 | click | xpath=(//a[@id='endpoint']/paper-item/yt-formatted-string)[18] | 
    driver.findElement(By.xpath("(//a[@id=\'endpoint\']/paper-item/yt-formatted-string)[18]")).click();
    // 10 | click | xpath=//div[@id='introduction-text']/div[2] | 
    driver.findElement(By.xpath("//div[@id=\'introduction-text\']/div[2]")).click();
    // 11 | click | linkText=принципы сообщества | 
    vars.put("window_handles", driver.getWindowHandles());
    // 12 | selectWindow | handle=${win332} | 
    driver.findElement(By.linkText("принципы сообщества")).click();
    vars.put("win332", waitForWindow(2000));
    driver.switchTo().window(vars.get("win332").toString());
  }

  @Test
  public void settingsTest() {
    // Test name: SettingsTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | xpath=//a[@id='logo']/div | 
    {
      WebElement element = driver.findElement(By.xpath("//a[@id=\'logo\']/div"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | xpath=//a[@id='logo']/div | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | click | xpath=//div[@id='start']/yt-icon-button[2] | 
    driver.findElement(By.xpath("//div[@id=\'start\']/yt-icon-button[2]")).click();
    // 6 | mouseOver | xpath=(//a[@id='logo']/div)[3] | 
    {
      WebElement element = driver.findElement(By.xpath("(//a[@id=\'logo\']/div)[3]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | click | xpath=(//a[@id='endpoint']/paper-item/yt-formatted-string)[17] | 
    driver.findElement(By.xpath("(//a[@id=\'endpoint\']/paper-item/yt-formatted-string)[17]")).click();
  }

  @Test
  public void subscriptionsTest() {
    // Test name: SubscriptionsTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | xpath=(//button[@id='button']/yt-icon)[2] | 
    driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[2]")).click();
    // 5 | mouseOut | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | xpath=(//a[@id='endpoint']/paper-item/yt-formatted-string)[3] | 
    driver.findElement(By.xpath("(//a[@id=\'endpoint\']/paper-item/yt-formatted-string)[3]")).click();
  }

  @Test
  public void trendingTest() {
    // Test name: TrendingTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | xpath=(//button[@id='button']/yt-icon)[2] | 
    driver.findElement(By.xpath("(//button[@id=\'button\']/yt-icon)[2]")).click();
    // 5 | mouseOut | xpath=(//button[@id='button']/yt-icon)[2] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | xpath=(//a[@id='endpoint']/paper-item/yt-formatted-string)[2] | 
    driver.findElement(By.xpath("(//a[@id=\'endpoint\']/paper-item/yt-formatted-string)[2]")).click();
  }
}
