// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
public class LibraryTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void libraryTest() {
    // Test name: LibraryTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.id("guide-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | id=guide-icon | 
    driver.findElement(By.id("guide-icon")).click();
    // 5 | mouseOut | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | mouseOver | css=#header > #guide-button #guide-icon | 
    {
      WebElement element = driver.findElement(By.cssSelector("#header > #guide-button #guide-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOut | css=#header > #guide-button #guide-icon | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | click | css=.style-scope:nth-child(2) > #items > .style-scope:nth-child(1) > #endpoint .title | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(2) > #items > .style-scope:nth-child(1) > #endpoint .title")).click();
  }
}
