// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
public class ReferenceTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void referenceTest() {
    // Test name: ReferenceTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.id("guide-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | id=guide-icon | 
    driver.findElement(By.id("guide-icon")).click();
    // 5 | mouseOut | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | mouseOver | css=.ytd-app > #logo > #logo-icon-container | 
    {
      WebElement element = driver.findElement(By.cssSelector(".ytd-app > #logo > #logo-icon-container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOut | css=.ytd-app > #logo > #logo-icon-container | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | mouseOver | css=.style-scope:nth-child(1) > #items > .style-scope:nth-child(2) > #endpoint .title | 
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(1) > #items > .style-scope:nth-child(2) > #endpoint .title"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | mouseOut | css=.style-scope:nth-child(1) > #items > .style-scope:nth-child(2) > #endpoint .title | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 10 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 11 | click | css=.style-scope:nth-child(7) > #items > .style-scope:nth-child(3) > #endpoint .title | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(7) > #items > .style-scope:nth-child(3) > #endpoint .title")).click();
    // 12 | mouseOver | css=.style-scope:nth-child(7) .style-scope:nth-child(2) > #endpoint > .style-scope | 
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(7) .style-scope:nth-child(2) > #endpoint > .style-scope"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 13 | selectFrame | index=2 | 
    driver.switchTo().frame(2);
    // 14 | selectFrame | index=1 | 
    driver.switchTo().frame(1);
    // 15 | click | css=.help-panel-home:nth-child(7) .help-panel-search__recommendation-results > .help-panel-search-result:nth-child(3) > .help-panel-search-result__text | 
    driver.findElement(By.cssSelector(".help-panel-home:nth-child(7) .help-panel-search__recommendation-results > .help-panel-search-result:nth-child(3) > .help-panel-search-result__text")).click();
    // 16 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 17 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 18 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 19 | selectFrame | index=2 | 
    driver.switchTo().frame(2);
    // 20 | selectFrame | index=1 | 
    driver.switchTo().frame(1);
    // 21 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 22 | selectFrame | index=8 | 
    driver.switchTo().frame(8);
    // 23 | click | css=.as-button:nth-child(1) | 
    driver.findElement(By.cssSelector(".as-button:nth-child(1)")).click();
  }
}
