// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class ReportsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = Util.getFirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void reportsTest() {
    // Test name: ReportsTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.id("guide-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | id=guide-icon | 
    driver.findElement(By.id("guide-icon")).click();
    // 5 | mouseOut | id=guide-icon | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | mouseOver | css=.ytd-app > #logo > #logo-icon-container | 
    {
      WebElement element = driver.findElement(By.cssSelector(".ytd-app > #logo > #logo-icon-container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOut | css=.ytd-app > #logo > #logo-icon-container | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 9 | click | css=.style-scope:nth-child(7) > #items > .style-scope:nth-child(2) > #endpoint .title | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(7) > #items > .style-scope:nth-child(2) > #endpoint .title")).click();
    // 10 | click | id=title | 
    driver.findElement(By.id("title")).click();
    // 11 | click | linkText=принципы сообщества | 
    vars.put("window_handles", driver.getWindowHandles());
    // 12 | selectWindow | handle=${win332} | 
    driver.findElement(By.linkText("принципы сообщества")).click();
    vars.put("win332", waitForWindow(2000));
    driver.switchTo().window(vars.get("win332").toString());
  }
}
