// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class SettingsTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = Util.getFirefoxDriver();
    js = (JavascriptExecutor) driver;
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void settingsTest() {
    // Test name: SettingsTest
    // Step # | name | target | value
    // 1 | open | https://www.youtube.com/watch?v=FFJfwEJQJzQ | 
    driver.get("https://www.youtube.com/watch?v=FFJfwEJQJzQ");
    // 2 | setWindowSize | 1098x691 | 
    driver.manage().window().setSize(new Dimension(1098, 691));
    // 3 | mouseOver | id=logo-icon-container | 
    {
      WebElement element = driver.findElement(By.id("logo-icon-container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | id=logo-icon-container | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | click | id=guide-button | 
    driver.findElement(By.id("guide-button")).click();
    // 6 | mouseOver | css=.ytd-app > #logo > #logo-icon-container | 
    {
      WebElement element = driver.findElement(By.cssSelector(".ytd-app > #logo > #logo-icon-container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | click | css=.style-scope:nth-child(7) > #items > .style-scope:nth-child(1) > #endpoint .title | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(7) > #items > .style-scope:nth-child(1) > #endpoint .title")).click();
  }
}
